### ISSUE TITLE
SQL Version in Veeam 9.5.4.2615 Update 4

### ISSUE THREAD

**Issue by bgre033** [vMarkusK/veeam_setup#6]
Hello,

The SQL version included in VBR v9.5 Update 4 is SQL 2016 SP**1**, which is the default download ISO specified for **vbr_url**. In **vbr_setup.yml** the path for the task **SQL - Install SQL Express 2016 SP2** is specified as "{{ vbr_source }}Redistr\\x64\\SqlExpress\\2016SP**2**\\SQLEXPR_x64_ENU.exe".

Easy enough to fix, but just so you know that the playbook will fail by default if running with **vbr_download: true**.

Cheers,

Gregor

**Comment by vMarkusK** [comment]
Hi Gregor,

Thanks for the Feedback.

- I am aware of the SQL version mismatch for older VBR versions. The current role is made for v10 RTM and will be updated (hopefully today) for GA

Do you think there should be an compatibility for older versions in the role? 

- I am already working on a new download. Veeam needs to serve a public download URL (they already did, but I am currently short on time) .

Is the current download URL down or is there an other issue?

**Comment by bgre033** [comment]
The 9.5 download URL works as expected. Not sure why I wrote the **vbr_download: true** part actually, as the play will fail whether you download or not, unless the SQL path is fixed.

Personally, I don't think it needs to support older versions. It might also be quite challenging as v10 requires .NET 4.7.2, which is the error I hit when trying to deploy v10 to Server 2016 using your playbook.

**Comment by vMarkusK** [comment]
Thanks for the hint regarding the .Net requirement. I have only tested on windows 2019

**Comment by vMarkusK** [comment]
Might please describe the the SQL Path isse a little bit more detailed?

Currently this option is hard coded. The version I am currently working on will change this.

**Comment by bgre033** [comment]
Sure. As you say, the SQL path is hard coded. This hard coded path contains SP2 in the path name ("{{ vbr_source }}Redistr\x64\SqlExpress\2016SP2\SQLEXPR_x64_ENU.exe") but it should be SP1 since the default ISO is 9.5 U4.

**Comment by vMarkusK** [comment]
Sorry, I misunderstood that. I thought you mean the SQL Instance... 

Which build of the  9.5 U4 ISO do you use? 

In the playbook for v10 RTM / GA (latest Version) the SQL Path ist already updated to SP2.

**Comment by bgre033** [comment]
Yep, so now that you've updated the defaults to download the v10 ISO, all should be ok :)
